### ISSUE TITLE
System can not find the route. : 'clips\\train\\ApplyEyeMakeup\\16.avi'

### ISSUE THREAD

**Issue by xiaoluenbi** [s-ankur/human-activity-dih18#5]
Hello, I am getting an error when running "Extract the dataset in a folder named videos in the dataset folder." The system cannot find the path specified. : 'clips\\train\\ApplyEyeMakeup\\16.avi'. I would like to ask you when the clips are automatically generated should be in the datasets path? My automatically generated clips file appears below the root directory, and there is no train and test. This problem has been bothering me for a long time, I hope you can help me solve it.

**Comment by s-ankur** [comment]
Yup Thanks, I've fixed it now.
You dont have to create any folder other than 'human-activity-dih18/ucf101/videos'

**Comment by xiaoluenbi** [comment]
Thank you very much, I solved my previous problem. But I appear when I run fit.py
Traceback (most recent call last):
  File "dataset.py", line 15, in <module>
    getattr(dataset, args.action)()
  File "F:\human-activity-dih18-master\datasets\ucf101.py", line 131, in extract
    frame = video.read()
  File "F:\human-activity-dih18-master\utility\cv_utils.py", line 113, in read
    raise ValueError("Videostream Not Working/ Existing")
ValueError: Videostream Not Working/ Existing
Is this a problem with the video?

**Comment by s-ankur** [comment]
Yes, Ive had this error
before, its a problem with your opencv install.

**Comment by xiaoluenbi** [comment]
>           Yes, Ive had this error
> before, its a problem with your opencv install.

I installed opencv3.4.3 directly in pycharm. Which way is your opencv installed?
